//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USF_Accom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public string RequestorID { get; set; }
        public string RequesteeID { get; set; }
        public int CommunityID { get; set; }
        public string AptNo { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
        public virtual StudentDetail StudentDetail1 { get; set; }
    }
}
